name: 'CloudPayments'
version: '2.0.0'
main: ru.clouddonate.cloudpayments.CloudPaymentsPlugin
api-version: 1.16
authors: [ CloudDonate Developers and Contributors ]
website: 'https://cdonate.ru'
commands:
  cloudpayments:
    aliases: [cpayments]
  cart: